[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@zetachain/protocol-contracts/=node_modules/@zetachain/protocol-contracts/",
    "@zetachain/standard-contracts/=node_modules/@zetachain/standard-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options